// This is the ONLY file that changes when you clone this module.
// See SCHEMA-SPEC.md for the full reference — quick version below.
// Rough cut auto-generated by db-cli.js (rule-based column-name matching,
// no AI) — hand-tune sections/profileActions/groupedSelect below same as
// any other cloned module.
//
// FRONTEND schema — full UI shape (showInList, profileActions, apiBase,
// rowLinks, customBlocks, sections, moduleRole, etc). The trimmed backend
// counterpart lives alongside this at the api/ path and only carries
// entity/fields/batchMutations/roles.

import { getApiRoutes } from '../AppRoutes/apiRoutesHandler';
import { resolveField } from '../DataControl/simukopaSchema';
import LocationTools from './uiControl/LocationTools';
// Use default base root (/)
const apiRoutes = getApiRoutes();
const moduleApi = apiRoutes.phones.base;

export const PhonesSchema = {
  entity: 'phones',              // DB table name; also drives default role names
                                     // (view_phones / manage_phones) and apiBase
  label: 'Device Inventory',                 // optional, defaults to entity capitalized
  apiBase: moduleApi,

  //api endpint for importing data from csv
  importDataEndpoint : apiRoutes.phones.import,

  // Page-level UI gate — checked once, for the WHOLE grid AND the WHOLE
  // profile/form page, via mosyACTRLHasRole. No moduleRole set -> open to
  // anyone (same additive convention as every other role/flag in this
  // file). This is a different layer than the per-action `role` flag
  // inside individual moduleActions entries below: moduleRole controls
  // whether someone can reach the page at all; a per-action role controls
  // whether one specific button shows up once they're already in. Same
  // UI-only caveat as those: route.js needs the equivalent server-side
  // check for this to be real enforcement, not just hiding.
  moduleRole: 'view_phones',


  gridOptions : {
   checkBoxes : false,
   checkFunction : "gridCheckBoxAction"  
  },

  multiGridRows: [
    // {
    //   key: 'order_items',
    //   parentTable: 'gps_logs',
    //   title: 'Log summary',
    //   columns: [
    //     { key: 'speed', label: 'Speed' },
    //     { key: 'latitude', label: 'Lat' },
    //     { key: 'longitude', label: 'Long' , sum: true},
    //     { key: 'remark', label: 'Selling price' }
    //   ],
    //   viewMoreLink: '../gpslogs/list',
    //   filter: { order_id: '{record_id}' },
    // },
  ],

  rowLinks: [],

  // Actions available from the list view, form and grid in display order.
  //{ 
  // key: 'filter_by_client', -- name of the action 
  // label: 'Filter by account', -- button label 
  // icon: 'user', -- icon of the buttons
  // grid:true, -- show on grid or not, 
  // type: 'action', -- indicates action on form registry 
  // form: false, -- show on form or not, 
  // rowAction: false --show on row drop down or not
  // variant : 'outline-primary', -- button color  variant
  // navigateTo: '/supererpv5/revenueplan/profile', -- route to navigate to -  for link buttons only 
  // colorClass:"bg-success text-white", -- button color classname 
  // confirm: 'Are you sure you want to delete this revenueplan?', -- confirmation message for delete button
  // editOnly: true, -- show on edit only or not
  // role: 'manage_revenueplan' -- role required for this action
  //},

  profileActions: [
    { key: 'back', label: 'Back to list', icon: 'arrow-left', variant: 'outline-secondary', navigateTo: '/simukopa/phones/list', grid: false, form: true },
    { key: 'save', label: 'Save', icon: 'save', variant: 'primary', grid: false, form: true, rowAction: false },
    { key: 'delete', label: 'Delete', icon: 'trash', variant: 'outline-danger', confirm: 'Are you sure you want to delete this phone?', editOnly: true, grid: false, form: true, rowAction: true, role: 'manage_phones' },
    { key: 'view', label: 'View more', icon: 'edit', rowAction: true },
    { key: 'update_status', label: 'Update Status', icon: 'refresh', rowAction: true, role: 'manage_phones' },
    { key: 'update_location', label: 'Update Location', icon: 'map-pin', rowAction: true, form: true, role: 'manage_phones' },
    { key: 'control_device', label: 'Control Device', icon: 'lock', rowAction: true, form: true, role: 'manage_phones' },
    { key: 'new', label: 'New Phone', icon: 'plus', variant: 'outline-primary', navigateTo: '/simukopa/phones/profile', grid: true, form: false, rowAction: false },
    { key: 'clone', label: 'Clone Record', icon: 'copy', variant: 'outline-secondary', editOnly: true, grid: false, form: true, rowAction: false, role: 'manage_phones' },
    //{ key: 'filterByDate', label: 'Filter by date', icon: 'calendar', variant: 'outline-primary', type: 'action', grid: true, form: false, rowAction: false },

    // Grid-toolbar smart filter — devices issued to a given client. Handler
    // in logicControl/actionsRegistry.js.
    { key: 'filter_by_client', label: 'Client Issued', icon: 'user', variant: 'outline-secondary', type: 'action', grid: true, form: false, rowAction: false },
    { key: 'filter_by_status', label: 'Status', icon: 'filter', variant: 'outline-secondary', type: 'action', grid: true, form: false, rowAction: false },

    // Pops a Google Map MosyCard centered on this device's saved location.
    // Handler in logicControl/actionsRegistry.js.
    { key: 'trace', label: 'Trace Location', icon: 'map-pin', variant: 'outline-secondary', type: 'action', editOnly: true, grid: false, form: true, rowAction: true },
  ],



  // customBlocks — the escape hatch for UI that doesn't fit the rigid
  // field-grid: a raw component, handed the SAME values/setValue/errors/
  // schema/isEditing/row context a real field gets. A block's `key` just
  // sits in a section's `fields` array exactly like a real field key —
  // wherever it appears there is where it renders. Empty by default;
  // uncomment and point at a real component when a field needs custom UI
  // (see SCHEMA-SPEC.md for the full pattern, e.g. companies/schema.js).
  customBlocks: [
    // Sits next to the `location` field — auto-fills it (once, if blank)
    // and gives a manual "Detect current location" button. See
    // uiControl/LocationTools.jsx for why this has to be a customBlock
    // rather than a profileActions entry (needs the live, unsaved
    // form's setValue, which actionsRegistry.js never gets).
    { key: 'location_actions', component: LocationTools, colSpan: 4 },
  ],

  fieldGroups: [],
  // Field keys shown as columns in list view, in display order.
  showInList: ['row_count', 'brand_name', 'model_name', 'imei_1', 'imei_2', 'serial_number', 'purchase_price', 'installment_price', 'status', 'lock_status', 'selling_price','client_name', 'loan_ref' ],

  //export columns these columns are used to generate upload csv template file
  exportColumns: ['photo', 'brand_name', 'model_name', 'imei_1', 'imei_2', 'serial_number', 'phone_number', 'purchase_price'],

  sections: [
    { key: 'basic_information', label: 'Basic Information', columns: 3, fields: ['photo', 'model_name', 'brand_name','imei_1', 'imei_2', 'serial_number','purchase_price', 'installment_price', 'selling_price' ] },
    { key: 'other_details', label: 'Other Details', columns: 3, fields: ['status', 'lock_status', 'condition_status', 'location', 'location_actions', 'assigned_client_id', 'assigned_loan_id', 'received_date', 'notes','allocated_date',  'reg_date'] },
  ],

  fields: [
    // key: DB column name | label: shown on screen | type: drives input + SQL type
    { key: 'primkey', label: 'Primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', label: 'Record Id', type: 'text', system: true, editable: false },
    { key: 'photo', label: 'Photo', type: 'image', colSpan: 12 },
    { key: 'model_name', label: 'Model name', type: 'groupedSelect', endpoint: moduleApi, groupByField: 'model_name' , title: true},
    { key: 'brand_name', label: 'Brand Name', type: 'groupedSelect', endpoint: moduleApi, groupByField: 'brand_name', title: true },
    { key: 'imei_1', label: 'Imei 1', type: 'text', title: true },
    { key: 'imei_2', label: 'Imei 2', type: 'text' },
    { key: 'selling_price', label: 'Selling Price', type: 'text' , sum: true},
    { key: 'installment_price', label: 'Installment Price', type: 'text' , sum: true},
    { key: 'serial_number', label: 'Serial Number', type: 'text' },
    { key: 'phone_number', label: 'Phone Number', type: 'text' },
    { key: 'purchase_price', label: 'Purchase Price', type: 'money' , sum: true},
    { key: 'status', label: 'Status', type: 'groupedSelect', endpoint: moduleApi, groupByField: 'status' },
    // Set only via the "Control Device" action (logicControl/actionsRegistry.js) — never hand-typed.
    { key: 'lock_status', label: 'Lock Status', type: 'select', options: ['unlocked', 'locked'], editable: false },
    { key: 'condition_status', label: 'Condition Status', type: 'text' },
    { key: 'location', label: 'Location', type: 'text' },
    // liveSearch picker (basic_information section) + its cached display
    // name (client_name/loan_ref, used in showInList) — both come from
    // globalRelations via resolveField, same convention imsv2 uses.
    // Usually set programmatically by the loan-allocation wizard, but
    // resolveField's liveSearch input has no readOnly/lock option, so this
    // now doubles as a manual reassignment picker if ever needed.
    ...resolveField('assigned_client_id', { as: 'client_name' }),
    ...resolveField('assigned_loan_id', { as: 'loan_ref' }, { label: 'Loan Ref' }),
    { key: 'received_date', label: 'Received Date', type: 'datetime' },
    { key: 'allocated_date', label: 'Allocated Date', type: 'datetime', editable: false },
    { key: 'notes', label: 'Notes', type: 'textarea', colSpan: 12 },
    { key: 'reg_date', label: 'Date Added', type: 'datetime', system: true, editable: false },
    { key: 'row_count', label: '#', type: 'number', computed: true, editable: false },
    //  live search field sample
    // { key: 'permissions', label: 'Permissions',
    //   type: 'liveSearch', colSpan: 6,
    //   endpoint: '/api/assetguard/systemmodules',
    //   searchTable: 'system_modules',
    //   valueField: 'record_id',      // id column on system_modules
    //   displayField: 'module_name',  // label column on system_modules — what search results/defaultValue text actually render
    //   labelKey: 'permission_name',  // cached label already joined onto THIS row (system_roles) — only used to seed defaultValue on load
    // },
    // more fields... see SCHEMA-SPEC.md for the full field option list
    // (searchable, editable, options, priority, db overrides)
  ],

  filters: [
    { key: 'all', label: 'All', query: {} },
  ],

  actions: [
    // { key: 'some_action', label: 'Do Something', appliesTo: { status: 'x' } },
    // "key" must match a function registered in lib/actionsRegistry.js
  ],

// for button color classes  
// dyn-btn-accent-amber  { border-color: transparent; color: #b45309; }
// dyn-btn-accent-green  { border-color: transparent; color: #047857; }
// dyn-btn-accent-purple { border-color: transparent; color: #6d28d9; }
// dyn-btn-accent-pink   { border-color: transparent; color: #be185d; }
// dyn-btn-accent-red    { border-color: transparent; color: #b91c1c; }
// dyn-btn-accent-yellow { border-color: transparent; color: #a16207; }
// dyn-btn-accent-blue   { border-color: transparent; color: #1d4ed8; }
// dyn-btn-accent-teal   { border-color: transparent; color: #0f766e; }

  // Optional: only needed if permission keys don't follow the
  // view_<entity> / manage_<entity> default.
  // roles: { view: 'view_phones', manage: 'manage_phones' },
};
