// Auto-generated by db-cli.js — BACKEND schema (trimmed).
// This is the data-shape-only counterpart to the frontend schema.js at the
// matching app/ path. It intentionally does NOT include showInList,
// profileActions, apiBase, rowLinks, customBlocks, sections, moduleRole,
// filters, or actions — those are UI concerns and live in the frontend
// schema only. Field entries also omit `label` here (UI-only display
// text) even though the frontend fields carry it. Edit
// fields/batchMutations/roles here; edit everything else there. Keep the
// `fields` array in sync between the two by regenerating both together
// (this tool writes both from the same column read).

export const ClientsSchema = {
  entity: 'clients',

  moduleRole: 'view_clients',

  fields: [
    // key: DB column name | type: drives SQL/validation (label omitted —
    // UI-only, lives in the frontend schema)
    { key: 'primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', type: 'text', system: true, editable: false },
    { key: 'client_number', type: 'text', searchable: true },
    { key: 'first_name', type: 'text', title: true, required: true, searchable: true },
    { key: 'middle_name', type: 'text', title: true, searchable: true },
    { key: 'last_name', type: 'text', title: true, required: true, searchable: true },
    { key: 'id_number', type: 'text', searchable: true },
    { key: 'id_type', type: 'text', searchable: true },
    { key: 'phone_number', type: 'text', searchable: true },
    { key: 'alternative_phone', type: 'text', searchable: true },
    { key: 'email', type: 'text', searchable: true },
    { key: 'date_of_birth', type: 'datetime' },
    { key: 'gender', type: 'text', searchable: true },
    { key: 'county', type: 'groupedSelect', endpoint: '/api/simukopa/clients/list', groupByField: 'county', searchable: true },
    { key: 'town', type: 'groupedSelect', endpoint: '/api/simukopa/clients/list', groupByField: 'town', searchable: true },
    { key: 'address', type: 'textarea', colSpan: 3, searchable: true },
    { key: 'occupation', type: 'text', searchable: true },
    { key: 'employer', type: 'text', searchable: true },
    { key: 'monthly_income', type: 'money' },
    { key: 'status', type: 'groupedSelect', endpoint: '/api/simukopa/clients/list', groupByField: 'status', searchable: true },
    { key: 'kyc_status', type: 'text', searchable: true },
    { key: 'notes', type: 'textarea', colSpan: 3, searchable: true },
    { key: 'created_by', type: 'text', searchable: true },
    { key: 'reg_date', type: 'datetime' },
    { key: 'hive_site_id', type: 'text', searchable: true },
    { key: 'hive_site_name', type: 'text', title: true, searchable: true },
    { key: 'photo', type: 'image' },
    { key: 'row_count', type: 'number', computed: true, editable: false },

    // Readonly loan-summary totals — resolved via batchMutations "sum"/
    // "compute" below, not real columns on this table.
    { key: 'total_issued', type: 'money', computed: true, editable: false },
    { key: 'total_paid', type: 'money', computed: true, editable: false },
    { key: 'balance', type: 'money', computed: true, editable: false },
  ],

  // Optional: joins enriching each row with data from another table.
  // Same shape as your existing *BatchMutations.js files.
  batchMutations: {
    // "_staff_full_name_staff_id": {
    //   type: "join", table: "staff", link: "staff_id:record_id",
    //   select: { "_staff_full_name_staff_id": "full_name" }
    // },

    // Sum of loans.total_amount issued to this client (loans.client_id -> clients.record_id).
    total_issued: {
      type: 'sum', table: 'loans', column: 'total_amount', link: 'client_id:record_id',
    },
    // Sum of payments.amount this client has paid (payments.client_id -> clients.record_id).
    total_paid: {
      type: 'sum', table: 'payments', column: 'amount', link: 'client_id:record_id',
    },
    // Derived from the two sums above — must stay defined AFTER them so
    // mosyEnrichFinalResponse has already populated both by the time this runs.
    balance: {
      type: 'compute', expr: 'total_issued - total_paid',
    },
  },

  roles: { view: 'view_clients', manage: 'manage_clients' },
};
