// This is the ONLY file that changes when you clone this module.
// See SCHEMA-SPEC.md for the full reference — quick version below.
// Rough cut auto-generated by db-cli.js (rule-based column-name matching,
// no AI) — hand-tune sections/profileActions/groupedSelect below same as
// any other cloned module.
//
// FRONTEND schema — full UI shape (showInList, profileActions, apiBase,
// rowLinks, customBlocks, sections, moduleRole, etc). The trimmed backend
// counterpart lives alongside this at the api/ path and only carries
// entity/fields/batchMutations/roles.

import { getApiRoutes } from '../AppRoutes/apiRoutesHandler';
import { resolveField } from '../DataControl/simukopaSchema';
// Use default base root (/)
const apiRoutes = getApiRoutes();
const moduleApi = apiRoutes.loanapplications.base;

export const LoanapplicationsSchema = {
  entity: 'loan_applications',              // DB table name; also drives default role names
                                     // (view_loanapplications / manage_loanapplications) and apiBase
  label: 'Loan applications',                 // optional, defaults to entity capitalized
  apiBase: moduleApi,

  //api endpint for importing data from csv
  importDataEndpoint : apiRoutes.loanapplications.import,

  // Page-level UI gate — checked once, for the WHOLE grid AND the WHOLE
  // profile/form page, via mosyACTRLHasRole. No moduleRole set -> open to
  // anyone (same additive convention as every other role/flag in this
  // file). This is a different layer than the per-action `role` flag
  // inside individual moduleActions entries below: moduleRole controls
  // whether someone can reach the page at all; a per-action role controls
  // whether one specific button shows up once they're already in. Same
  // UI-only caveat as those: route.js needs the equivalent server-side
  // check for this to be real enforcement, not just hiding.
  moduleRole: 'view_loanapplications',


  gridOptions : {
   checkBoxes : false,
   checkFunction : "gridCheckBoxAction"  
  },

  multiGridRows: [
    // {
    //   key: 'order_items',
    //   parentTable: 'gps_logs',
    //   title: 'Log summary',
    //   columns: [
    //     { key: 'speed', label: 'Speed' },
    //     { key: 'latitude', label: 'Lat' },
    //     { key: 'longitude', label: 'Long' , sum: true},
    //     { key: 'remark', label: 'Selling price' }
    //   ],
    //   viewMoreLink: '../gpslogs/list',
    //   filter: { order_id: '{record_id}' },
    // },
  ],

  rowLinks: [],

  // Actions available from the list view, form and grid in display order.
  //{ 
  // key: 'filter_by_client', -- name of the action 
  // label: 'Filter by account', -- button label 
  // icon: 'user', -- icon of the buttons
  // grid:true, -- show on grid or not, 
  // type: 'action', -- indicates action on form registry 
  // form: false, -- show on form or not, 
  // rowAction: false --show on row drop down or not
  // variant : 'outline-primary', -- button color  variant
  // navigateTo: '/supererpv5/revenueplan/profile', -- route to navigate to -  for link buttons only 
  // colorClass:"bg-success text-white", -- button color classname 
  // confirm: 'Are you sure you want to delete this revenueplan?', -- confirmation message for delete button
  // editOnly: true, -- show on edit only or not
  // role: 'manage_revenueplan' -- role required for this action
  //},

  profileActions: [
    { key: 'back', label: 'Back to list', icon: 'arrow-left', variant: 'outline-secondary', navigateTo: '/simukopa/loanapplications/list', grid: false, form: true },
    { key: 'save', label: 'Save', icon: 'save', variant: 'primary', grid: false, form: true, rowAction: false },
    { key: 'delete', label: 'Delete', icon: 'trash', variant: 'outline-danger', confirm: 'Are you sure you want to delete this loanapplication?', editOnly: true, grid: false, form: true, rowAction: true, role: 'manage_loanapplications' },
    { key: 'view', label: 'View more', icon: 'edit', rowAction: true },
    { key: 'new', label: 'New application', icon: 'plus', variant: 'outline-primary', navigateTo: '/simukopa/loanallocation', grid: true, form: false, rowAction: false },
    { key: 'clone', label: 'Clone Record', icon: 'copy', variant: 'outline-secondary', editOnly: true, grid: false, form: true, rowAction: false, role: 'manage_loanapplications' },

    // Grid-toolbar smart filters (combine, so they AND together) — handlers in logicControl/actionsRegistry.js.
    { key: 'filter_by_client', label: 'Client', icon: 'user', variant: 'outline-secondary', type: 'action', grid: true, form: false, rowAction: false },
    { key: 'filter_by_product', label: 'Product', icon: 'tag', variant: 'outline-secondary', type: 'action', grid: true, form: false, rowAction: false },
    { key: 'filter_by_date', label: 'Date', icon: 'calendar', variant: 'outline-secondary', type: 'action', grid: true, form: false, rowAction: false },
    { key: 'filter_by_status', label: 'Status', icon: 'filter', variant: 'outline-secondary', type: 'action', grid: true, form: false, rowAction: false },

    // Jump to the linked records' own profiles/list — handlers in
    // logicControl/actionsRegistry.js.
    { key: 'view_client', label: 'View Client', icon: 'user', variant: 'outline-secondary', type: 'action', editOnly: true, grid: false, form: true, rowAction: true },
    { key: 'view_device', label: 'View Device', icon: 'smartphone', variant: 'outline-secondary', type: 'action', editOnly: true, grid: false, form: true, rowAction: true },
    { key: 'view_messages', label: 'View Messages', icon: 'message-square', variant: 'outline-secondary', type: 'action', editOnly: true, grid: false, form: true, rowAction: true },
  ],



  // customBlocks — the escape hatch for UI that doesn't fit the rigid
  // field-grid: a raw component, handed the SAME values/setValue/errors/
  // schema/isEditing/row context a real field gets. A block's `key` just
  // sits in a section's `fields` array exactly like a real field key —
  // wherever it appears there is where it renders. Empty by default;
  // uncomment and point at a real component when a field needs custom UI
  // (see SCHEMA-SPEC.md for the full pattern, e.g. companies/schema.js).
  customBlocks: [
    // { key: 'some_field', component: SomeComponent, colSpan: 7 },
  ],

  fieldGroups: [],
  // Field keys shown as columns in list view, in display order. The
  // *_name columns are display-only (computed, see fields[] below) —
  // client_id/phone_id/model_id/product_id stay on every row for actions/
  // relationships, they're just not shown as their own columns anymore.
  showInList: ['row_count', 'application_id', 'client_name', 'phone_name', 'model_name', 'product_name', 'requested_amount', 'deposit_amount', 'amount_paid', 'balance', 'next_billing_date', 'status', 'application_date'],

  //export columns these columns are used to generate upload csv template file
  exportColumns: ['application_id', 'client_id', 'phone_id', 'model_id', 'product_id', 'requested_amount', 'deposit_amount'],

  sections: [
    { key: 'basic_information', label: 'Basic Information', columns: 3, fields: ['application_id', 'client_id', 'phone_id', 'model_id', 'product_name', 'requested_amount', 'deposit_amount'] },
    { key: 'other_details', label: 'Other Details', columns: 3, fields: ['application_date', 'approval_date', 'approved_amount', 'rejection_reason', 'status', 'next_billing_date', 'notes', 'reg_date'] },
    { key: 'payment_summary', label: 'Payment Summary', columns: 3, fields: ['amount_paid', 'balance'] },
  ],

  fields: [
    // key: DB column name | label: shown on screen | type: drives input + SQL type
    { key: 'primkey', label: 'Primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', label: 'Record Id', type: 'text', system: true, editable: false },
    // liveSearch pickers (basic_information section) + their cached
    // display names (client_name/phone_name/model_name, used in
    // showInList) — resolved from globalRelations via resolveField, same
    // convention imsv2 uses. Usually set by the loan-allocation wizard,
    // but resolveField's liveSearch input has no readOnly/lock option, so
    // these now double as manual reassignment pickers if ever needed.
    ...resolveField('client_id', { as: 'client_name' , colSpan: 4 }),
    ...resolveField('phone_id', { as: 'phone_name' ,label: 'Phone / Device' , colSpan: 4 }),
    // NOT resolveField('product_id', ...) — see the matching comment on
    // productJoin in the backend schema.js: globalRelations' product_id
    // entry points at the wrong table (financing_products instead of
    // loan_plans), so this stays a plain hidden FK + hand-resolved
    // product_name below until that spec entry is fixed.
    { key: 'product_id', label: 'Product Id', type: 'hidden', editable: false },
    { key :"next_billing_date", label: 'Next Billing Date', type: 'datetime' },
    { key: 'requested_amount', label: 'Purchase Price', type: 'money' , sum:true },
    { key: 'deposit_amount', label: 'Deposit Amount', type: 'money' },
    { key: 'application_date', label: 'Application Date', type: 'datetime' },
    { key: 'approval_date', label: 'Approval Date', type: 'datetime' },
    { key: 'approved_amount', label: 'Approved Amount', type: 'money' },
    { key: 'rejection_reason', label: 'Rejection Reason', type: 'textarea', colSpan:12 },
    { key: 'status', label: 'Status', type: 'groupedSelect', endpoint: moduleApi, groupByField: 'status' },
    { key: 'reviewed_by', label: 'Reviewed By', type: 'text' },
    { key: 'notes', label: 'Notes', type: 'textarea', colSpan: 12 },
    { key: 'reg_date', label: 'Creation Date', type: 'datetime' },
    { key: 'row_count', label: '#', type: 'number', computed: true, editable: false },

    // product_id has no globalRelations entry that points at the right
    // table (see comment above) — resolved by hand via productJoin
    // (api schema.js) instead of resolveField.
    { key: 'product_name', label: 'Product', type: 'text', computed: true, editable: false },

    // Readonly payment-summary totals — resolved server-side via
    // batchMutations "join"/"sum"/"compute" (api schema.js): sum of
    // payments against the loan this application produced, and what's
    // left of approved_amount (falling back to requested_amount pre-
    // approval) after that.
    { key: 'amount_paid', label: 'Amount Paid', type: 'money', computed: true, editable: false, sum: true },
    { key: 'balance', label: 'Balance', type: 'money', computed: true, editable: false, sum: true },
    //  live search field sample 
    // { key: 'permissions', label: 'Permissions',
    //   type: 'liveSearch', colSpan: 6,
    //   endpoint: '/api/assetguard/systemmodules',
    //   searchTable: 'system_modules',
    //   valueField: 'record_id',      // id column on system_modules
    //   displayField: 'module_name',  // label column on system_modules — what search results/defaultValue text actually render
    //   labelKey: 'permission_name',  // cached label already joined onto THIS row (system_roles) — only used to seed defaultValue on load
    // },
    // more fields... see SCHEMA-SPEC.md for the full field option list
    // (searchable, editable, options, priority, db overrides)
  ],

  filters: [
    { key: 'all', label: 'All', query: {} },
  ],

  actions: [
    // { key: 'some_action', label: 'Do Something', appliesTo: { status: 'x' } },
    // "key" must match a function registered in lib/actionsRegistry.js
  ],

// for button color classes  
// dyn-btn-accent-amber  { border-color: transparent; color: #b45309; }
// dyn-btn-accent-green  { border-color: transparent; color: #047857; }
// dyn-btn-accent-purple { border-color: transparent; color: #6d28d9; }
// dyn-btn-accent-pink   { border-color: transparent; color: #be185d; }
// dyn-btn-accent-red    { border-color: transparent; color: #b91c1c; }
// dyn-btn-accent-yellow { border-color: transparent; color: #a16207; }
// dyn-btn-accent-blue   { border-color: transparent; color: #1d4ed8; }
// dyn-btn-accent-teal   { border-color: transparent; color: #0f766e; }

  // Optional: only needed if permission keys don't follow the
  // view_<entity> / manage_<entity> default.
  // roles: { view: 'view_loanapplications', manage: 'manage_loanapplications' },
};
