// Auto-generated by db-cli.js — BACKEND schema (trimmed).
// This is the data-shape-only counterpart to the frontend schema.js at the
// matching app/ path. It intentionally does NOT include showInList,
// profileActions, apiBase, rowLinks, customBlocks, sections, moduleRole,
// filters, or actions — those are UI concerns and live in the frontend
// schema only. Field entries also omit `label` here (UI-only display
// text) even though the frontend fields carry it. Edit
// fields/batchMutations/roles here; edit everything else there. Keep the
// `fields` array in sync between the two by regenerating both together
// (this tool writes both from the same column read).

export const LoanplansSchema = {
  entity: 'loan_plans',

  moduleRole: 'view_loan_plans',

  fields: [
    // key: DB column name | type: drives SQL/validation (label omitted —
    // UI-only, lives in the frontend schema)
    { key: 'primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', type: 'text', system: true, editable: false },
    { key: 'plan_name', type: 'text', title: true, required: true, searchable: true },
    { key: 'device_model_group', type: 'text', searchable: true },
    { key: 'device_cost_price', type: 'money' },
    { key: 'deposit_amount', type: 'money' },
    { key: 'repayment_frequency', type: 'text', searchable: true },
    { key: 'installment_amount', type: 'money' },
    { key: 'duration_count', type: 'text' },
    { key: 'total_loan_cost', type: 'text' },
    { key: 'is_active', type: 'boolean' },
    { key: 'reg_date', type: 'datetime' },
    { key: 'hive_site_id', type: 'text', searchable: true },
    { key: 'hive_site_name', type: 'text', title: true, searchable: true },
    { key: 'row_count', type: 'number', computed: true, editable: false },
  ],

  // Optional: joins enriching each row with data from another table.
  // Same shape as your existing *BatchMutations.js files.
  batchMutations: {
    // "_staff_full_name_staff_id": {
    //   type: "join", table: "staff", link: "staff_id:record_id",
    //   select: { "_staff_full_name_staff_id": "full_name" }
    // },
  },

  roles: { view: 'view_loanplans', manage: 'manage_loanplans' },
};
