// simukopaSchema.js
// -------------------------------------------------------------------
// AUTO-GENERATED by schemamap.js from app\simukopa\schemamap.txt — do not hand-edit
// the globalRelations object below. Edit the spec file and rerun:
//   node schemamap.js
//
// Column name on a specific module differs from the relation key (e.g.
// a polymorphic "__" key, or a renamed FK column) — pass 'key' in
// overrides so both sides stay in sync.
// Override ANYTHING else per-module the same way — second arg always
// wins, shallow merge over the global default.
// Unknown relation key throws instead of silently returning undefined
// (fail loud, not silent).
//
// endpoint (frontend only) resolves live via apiRoutes.json/getApiRoutes,
// keyed by table.replace(/_/g, '') — the SAME default routeKey db-cli.js
// writes when it builds that table's own schema.js. If that table's
// schema was built with a custom --list-name prefix, its real
// apiRoutes.json key won't match this guess — hand-fix that one entry's
// endpoint here (or re-point it at a literal string) rather than
// regenerating; schemamap.js has no way to know about a prefix chosen in
// a different tool's run.
// -------------------------------------------------------------------

import { getApiRoutes } from '../AppRoutes/apiRoutesHandler';
const apiRoute = getApiRoutes();

export const globalRelations = {

  agent_id: {
    table: "agents",
    endpoint: apiRoute.agents.base,
    valueField: "record_id",
    displayField: "full_name",
    cacheField: "full_name",
    label: "Agent",
    // used by: commissions
  },

  allocated_by: {
    table: "system_users",
    endpoint: apiRoute.systemusers.base,
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: device_allocations
  },

  application_id: {
    table: "loan_applications",
    endpoint: apiRoute.loanapplications.base,
    valueField: "record_id",
    displayField: "application_id",
    cacheField: "application_id",
    label: "Application",
    // used by: loans
  },

  approved_by: {
    table: "system_users",
    endpoint: apiRoute.systemusers.base,
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: loans
  },

  assigned_client_id: {
    table: "clients",
    endpoint: apiRoute.clients.base,
    valueField: "record_id",
    displayField: "first_name",
    cacheField: "first_name",
    label: "Client",
    // used by: phones
  },

  assigned_loan_id: {
    table: "loans",
    endpoint: apiRoute.loans.base,
    valueField: "record_id",
    displayField: "loan_id",
    cacheField: "loan_id",
    label: "Loan",
    // used by: phones
  },

  bundle_id: {
    table: "system_role_bundles",
    endpoint: apiRoute.systemrolebundles.base,
    valueField: "record_id",
    displayField: "bundle_name",
    cacheField: "bundle_name",
    label: "Bundle",
    // used by: user_bundle_role_functions
  },

  client_id: {
    table: "clients",
    endpoint: apiRoute.clients.base,
    valueField: "record_id",
    displayField: "first_name",
    cacheField: "first_name",
    label: "Client",
    // used by: client_documents, collection_actions, commissions, device_allocations, device_events, guarantors, loan_applications, loan_installments, loans, notifications, payments
  },

  created_by: {
    table: "system_users",
    endpoint: apiRoute.systemusers.base,
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: client_documents, clients, collection_actions, inventory_transactions, payment_allocations, payments, smart_message_templates, smart_payment_requests, smart_payment_settings
  },

  initiated_by: {
    table: "system_users",
    endpoint: apiRoute.systemusers.base,
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: smart_calls
  },

  installment_id: {
    table: "loan_installments",
    endpoint: apiRoute.loaninstallments.base,
    valueField: "record_id",
    displayField: "installment_id",
    cacheField: "installment_id",
    label: "Installment",
    // used by: collection_actions, notifications, payment_allocations, payments
  },

  last_updated_by: {
    table: "system_users",
    endpoint: apiRoute.systemusers.base,
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: smart_message_templates, smart_payment_settings
  },

  loan_id: {
    table: "loans",
    endpoint: apiRoute.loans.base,
    valueField: "record_id",
    displayField: "loan_id",
    cacheField: "loan_id",
    label: "Loan",
    // used by: collection_actions, commissions, device_allocations, device_events, loan_installments, notifications, payment_allocations, payments
  },

  model_id: {
    table: "phone_models",
    endpoint: apiRoute.phonemodels.base,
    valueField: "record_id",
    displayField: "model_name",
    cacheField: "model_name",
    label: "Model",
    // used by: inventory_transactions, loan_applications, loans
  },

  module_id: {
    table: "system_modules",
    endpoint: apiRoute.systemmodules.base,
    valueField: "record_id",
    displayField: "module_name",
    cacheField: "module_name",
    label: "Module",
    // used by: system_role_permissions
  },

  payment_id: {
    table: "payments",
    endpoint: apiRoute.payments.base,
    valueField: "record_id",
    displayField: "payment_id",
    cacheField: "payment_id",
    label: "Payment",
    // used by: commissions, payment_allocations
  },

  phone_id: {
    table: "phones",
    endpoint: apiRoute.phones.base,
    valueField: "record_id",
    displayField: "model_name",
    cacheField: "model_name",
    label: "Phone",
    // used by: device_allocations, device_events, inventory_transactions, loan_applications, loans
  },

  processed_by: {
    table: "system_users",
    endpoint: apiRoute.systemusers.base,
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: smart_payments
  },

  product_id: {
    table: "financing_products",
    endpoint: apiRoute.financingproducts.base,
    valueField: "record_id",
    displayField: "product_name",
    cacheField: "product_name",
    label: "Product",
    // used by: loan_applications, loans
  },

  related_record_id__clients: {
    table: "clients",
    endpoint: apiRoute.clients.base,
    valueField: "record_id",
    displayField: "first_name",
    cacheField: "first_name",
    label: "Client",
    // polymorphic "related_record_id" — see other __ variants for its other targets
    // used by: smart_calls, smart_messages
  },

  related_record_id__smart_payments: {
    table: "smart_payments",
    endpoint: apiRoute.smartpayments.base,
    valueField: "record_id",
    displayField: "payment_reference",
    cacheField: "payment_reference",
    label: "Payment",
    // polymorphic "related_record_id" — see other __ variants for its other targets
    // used by: smart_payment_requests
  },

  related_record_id__system_modules: {
    table: "system_modules",
    endpoint: apiRoute.systemmodules.base,
    valueField: "record_id",
    displayField: "module_name",
    cacheField: "module_name",
    label: "Module",
    // polymorphic "related_record_id" — see other __ variants for its other targets
    // used by: mosy_reminders
  },

  reminder_id: {
    table: "mosy_reminders",
    endpoint: apiRoute.mosyreminders.base,
    valueField: "record_id",
    displayField: "reminder_id",
    cacheField: "reminder_id",
    label: "Reminder",
    // used by: mosy_reminder_log
  },

  request_reference: {
    table: "smart_payment_requests",
    endpoint: apiRoute.smartpaymentrequests.base,
    valueField: "request_reference",
    displayField: "request_title",
    cacheField: "request_title",
    label: "Request",
    // used by: smart_payments
  },

  requested_by: {
    table: "system_users",
    endpoint: apiRoute.systemusers.base,
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: device_events
  },

  reviewed_by: {
    table: "system_users",
    endpoint: apiRoute.systemusers.base,
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: loan_applications
  },

  role_id__roles: {
    table: "roles",
    endpoint: apiRoute.roles.base,
    valueField: "record_id",
    displayField: "role_name",
    cacheField: "role_name",
    label: "Role",
    // polymorphic "role_id" — see other __ variants for its other targets
    // used by: users
  },

  role_id__system_roles: {
    table: "system_roles",
    endpoint: apiRoute.systemroles.base,
    valueField: "record_id",
    displayField: "role_name",
    cacheField: "role_name",
    label: "Role",
    // polymorphic "role_id" — see other __ variants for its other targets
    // used by: system_role_permissions, user_bundle_role_functions, user_manifest_
  },

  sent_by: {
    table: "system_users",
    endpoint: apiRoute.systemusers.base,
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: smart_messages
  },

  user_id: {
    table: "system_users",
    endpoint: apiRoute.systemusers.base,
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: audit_logs, user_manifest_
  },

  user_role: {
    table: "system_roles",
    endpoint: apiRoute.systemroles.base,
    valueField: "record_id",
    displayField: "role_name",
    cacheField: "role_name",
    label: "Role",
    // used by: system_users
  },

};

function cacheKeyFor(rel, columnKey) {
  return `_${rel.table}_${rel.cacheField}_${columnKey}`;
}

function getRelation(relationKey, fnName) {
  const rel = globalRelations[relationKey];
  if (!rel) {
    throw new Error(
      `${fnName}: no globalRelations entry for "${relationKey}". ` +
      `Regenerate from schemamap.txt, or define this field/join locally instead.`
    );
  }
  return rel;
}

// ALWAYS returns an array — spread it into fields: every time, even when
// you're only expecting one field back. Consistent shape regardless of
// arguments means you can never forget the spread and end up with a stray
// nested array sitting inside fields: (which would silently corrupt the
// module — arrays aren't valid field entries).
//
//     ...resolveField('staff_id')
//     ...resolveField('related_record_id__app_users', { key: 'related_record_id', label: 'User Profile' })
//
// Pass 'as' to ALSO get a second, plain display field for the cached
// value itself — e.g. so "station_name" shows up in showInList/sections
// as its own field, not just as the liveSearch dropdown's hidden cache.
// Third arg overrides that second field (key/label/type/title/required/
// anything) — defaults to a read-only text field if you don't:
//
//     ...resolveField('fuel_station_id', { as: 'station_name' }, { label: 'Station Name', title: true, required: true })
//     -> [ { key: 'fuel_station_id', type: 'liveSearch', ... },
//          { key: 'station_name', label: 'Station Name', type: 'text', title: true, required: true } ]
//
// Pass the SAME 'as' value to resolveJoin on the backend side so both
// stay pointed at the same cached column on the row.
export function resolveField(relationKey, overrides = {}, displayOverrides = {}) {
  const rel = getRelation(relationKey, 'resolveField');
  const columnKey = overrides.key || relationKey;
  const cacheKey = overrides.as || cacheKeyFor(rel, columnKey);

  const { as: _unusedAs, ...restFieldOverrides } = overrides;
  const liveSearchField = {
    key: columnKey,
    label: rel.label,
    type: 'liveSearch',
    colSpan: 6,
    endpoint: rel.endpoint,
    searchTable: rel.table,
    valueField: rel.valueField,
    displayField: rel.displayField,
    labelKey: cacheKey,
    ...restFieldOverrides,
  };

  if (!overrides.as) {
    return [liveSearchField];
  }

  const cachedDisplayField = {
    key: cacheKey,
    label: rel.label,
    type: 'text',
    computed: true,
    editable: false,
    ...displayOverrides,
  };

  return [liveSearchField, cachedDisplayField];
}

// ---------------------------------------------------------------------
// Detected "reverse" relations (record_id referenced FROM another table).
// These are candidate multiGridRows / child-grid wiring, NOT parent
// lookups, so they are not turned into resolveField/resolveJoin entries.
// Wire manually into multiGridRows on the parent module's schema.js.
// ---------------------------------------------------------------------
// (none detected in this spec)
