// simukopaSchema.js
// -------------------------------------------------------------------
// AUTO-GENERATED by schemamap.js from app\simukopa\schemamap.txt — do not hand-edit
// the globalRelations object below. Edit the spec file and rerun:
//   node schemamap.js
//
// Column name on a specific module differs from the relation key (e.g.
// a polymorphic "__" key, or a renamed FK column) — pass 'key' in
// overrides so both sides stay in sync.
// Override ANYTHING else per-module the same way — second arg always
// wins, shallow merge over the global default.
// Unknown relation key throws instead of silently returning undefined
// (fail loud, not silent).
//
// endpoint (frontend only) resolves live via apiRoutes.json/getApiRoutes,
// keyed by table.replace(/_/g, '') — the SAME default routeKey db-cli.js
// writes when it builds that table's own schema.js. If that table's
// schema was built with a custom --list-name prefix, its real
// apiRoutes.json key won't match this guess — hand-fix that one entry's
// endpoint here (or re-point it at a literal string) rather than
// regenerating; schemamap.js has no way to know about a prefix chosen in
// a different tool's run.
// -------------------------------------------------------------------

export const globalRelations = {

  agent_id: {
    table: "agents",
    valueField: "record_id",
    displayField: "full_name",
    cacheField: "full_name",
    label: "Agent",
    // used by: commissions
  },

  allocated_by: {
    table: "system_users",
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: device_allocations
  },

  application_id: {
    table: "loan_applications",
    valueField: "record_id",
    displayField: "application_id",
    cacheField: "application_id",
    label: "Application",
    // used by: loans
  },

  approved_by: {
    table: "system_users",
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: loans
  },

  assigned_client_id: {
    table: "clients",
    valueField: "record_id",
    displayField: "first_name",
    cacheField: "first_name",
    label: "Client",
    // used by: phones
  },

  assigned_loan_id: {
    table: "loans",
    valueField: "record_id",
    displayField: "record_id",
    cacheField: "record_id",
    label: "Loan",
    // used by: phones
  },

  bundle_id: {
    table: "system_role_bundles",
    valueField: "record_id",
    displayField: "bundle_name",
    cacheField: "bundle_name",
    label: "Bundle",
    // used by: user_bundle_role_functions
  },

  client_id: {
    table: "clients",
    valueField: "record_id",
    displayField: "first_name",
    cacheField: "first_name",
    label: "Client",
    // used by: client_documents, collection_actions, commissions, device_allocations, device_events, guarantors, loan_applications, loan_installments, loans, notifications, payments
  },

  created_by: {
    table: "system_users",
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: client_documents, clients, collection_actions, inventory_transactions, payment_allocations, payments, smart_message_templates, smart_payment_requests, smart_payment_settings
  },

  initiated_by: {
    table: "system_users",
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: smart_calls
  },

  installment_id: {
    table: "loan_installments",
    valueField: "record_id",
    displayField: "installment_id",
    cacheField: "installment_id",
    label: "Installment",
    // used by: collection_actions, notifications, payment_allocations, payments
  },

  last_updated_by: {
    table: "system_users",
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: smart_message_templates, smart_payment_settings
  },

  loan_id: {
    table: "loans",
    valueField: "record_id",
    displayField: "record_id",
    cacheField: "record_id",
    label: "Loan",
    // used by: collection_actions, commissions, device_allocations, device_events, loan_installments, notifications, payment_allocations, payments
  },

  model_id: {
    table: "phone_models",
    valueField: "record_id",
    displayField: "model_name",
    cacheField: "model_name",
    label: "Model",
    // used by: inventory_transactions, loan_applications, loans
  },

  module_id: {
    table: "system_modules",
    valueField: "record_id",
    displayField: "module_name",
    cacheField: "module_name",
    label: "Module",
    // used by: system_role_permissions
  },

  payment_id: {
    table: "payments",
    valueField: "record_id",
    displayField: "payment_id",
    cacheField: "payment_id",
    label: "Payment",
    // used by: commissions, payment_allocations
  },

  phone_id: {
    table: "phones",
    valueField: "record_id",
    displayField: "model_name",
    cacheField: "model_name",
    label: "Phone",
    // used by: device_allocations, device_events, inventory_transactions, loan_applications, loans
  },

  processed_by: {
    table: "system_users",
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: smart_payments
  },

  product_id: {
    table: "financing_products",
    valueField: "record_id",
    displayField: "product_name",
    cacheField: "product_name",
    label: "Product",
    // used by: loan_applications, loans
  },

  related_record_id__clients: {
    table: "clients",
    valueField: "record_id",
    displayField: "first_name",
    cacheField: "first_name",
    label: "Client",
    // polymorphic "related_record_id" — see other __ variants for its other targets
    // used by: smart_calls, smart_messages
  },

  related_record_id__smart_payments: {
    table: "smart_payments",
    valueField: "record_id",
    displayField: "payment_reference",
    cacheField: "payment_reference",
    label: "Payment",
    // polymorphic "related_record_id" — see other __ variants for its other targets
    // used by: smart_payment_requests
  },

  related_record_id__system_modules: {
    table: "system_modules",
    valueField: "record_id",
    displayField: "module_name",
    cacheField: "module_name",
    label: "Module",
    // polymorphic "related_record_id" — see other __ variants for its other targets
    // used by: mosy_reminders
  },

  reminder_id: {
    table: "mosy_reminders",
    valueField: "record_id",
    displayField: "reminder_id",
    cacheField: "reminder_id",
    label: "Reminder",
    // used by: mosy_reminder_log
  },

  request_reference: {
    table: "smart_payment_requests",
    valueField: "request_reference",
    displayField: "request_title",
    cacheField: "request_title",
    label: "Request",
    // used by: smart_payments
  },

  requested_by: {
    table: "system_users",
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: device_events
  },

  reviewed_by: {
    table: "system_users",
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: loan_applications
  },

  role_id__roles: {
    table: "roles",
    valueField: "record_id",
    displayField: "role_name",
    cacheField: "role_name",
    label: "Role",
    // polymorphic "role_id" — see other __ variants for its other targets
    // used by: users
  },

  role_id__system_roles: {
    table: "system_roles",
    valueField: "record_id",
    displayField: "role_name",
    cacheField: "role_name",
    label: "Role",
    // polymorphic "role_id" — see other __ variants for its other targets
    // used by: system_role_permissions, user_bundle_role_functions, user_manifest_
  },

  sent_by: {
    table: "system_users",
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: smart_messages
  },

  user_id: {
    table: "system_users",
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: audit_logs, user_manifest_
  },

  user_role: {
    table: "system_roles",
    valueField: "record_id",
    displayField: "role_name",
    cacheField: "role_name",
    label: "Role",
    // used by: system_users
  },

};

function cacheKeyFor(rel, columnKey) {
  return `_${rel.table}_${rel.cacheField}_${columnKey}`;
}

function getRelation(relationKey, fnName) {
  const rel = globalRelations[relationKey];
  if (!rel) {
    throw new Error(
      `${fnName}: no globalRelations entry for "${relationKey}". ` +
      `Regenerate from schemamap.txt, or define this field/join locally instead.`
    );
  }
  return rel;
}

// Use it on the BACKEND schema (in 'batchMutations:'):
//     ...resolveJoin('staff_id')
//     ...resolveJoin('related_record_id__app_users', { key: 'related_record_id' })
//
// Cache alias too long/ugly (e.g. "_fuel_stations_station_name_fuel_station_id")?
// Override it with 'as' — pass the SAME 'as' value to resolveField on the
// frontend side so the two stay pointed at the same column on the row:
//     ...resolveJoin('fuel_station_id', { as: 'station_name' })
export function resolveJoin(relationKey, overrides = {}) {
  const rel = getRelation(relationKey, 'resolveJoin');
  const columnKey = overrides.key || relationKey;
  const cacheKey = overrides.as || cacheKeyFor(rel, columnKey);
  const descriptor = {
    type: 'join',
    table: rel.table,
    link: `${columnKey}:${rel.valueField}`,
    select: { [cacheKey]: rel.cacheField },
  };
  const { key: _unusedKey, as: _unusedAs, ...restOverrides } = overrides;
  return { [cacheKey]: { ...descriptor, ...restOverrides } };
}

// ---------------------------------------------------------------------
// Detected "reverse" relations (record_id referenced FROM another table).
// These are candidate multiGridRows / child-grid wiring, NOT parent
// lookups, so they are not turned into resolveField/resolveJoin entries.
// Wire manually into multiGridRows on the parent module's schema.js.
// ---------------------------------------------------------------------
// (none detected in this spec)
