// This is the ONLY file that changes when you clone this module.
// See SCHEMA-SPEC.md for the full reference — quick version below.
// Rough cut auto-generated by db-cli.js (rule-based column-name matching,
// no AI) — hand-tune sections/profileActions/groupedSelect below same as
// any other cloned module.
//
// FRONTEND schema — full UI shape (showInList, profileActions, apiBase,
// rowLinks, customBlocks, sections, moduleRole, etc). The trimmed backend
// counterpart lives alongside this at the api/ path and only carries
// entity/fields/batchMutations/roles.

import { getApiRoutes } from '../AppRoutes/apiRoutesHandler';
import { resolveField } from '../DataControl/simukopaSchema';
// Use default base root (/)
const apiRoutes = getApiRoutes();
const moduleApi = apiRoutes.payments.base;

export const PaymentsSchema = {
  entity: 'payments',              // DB table name; also drives default role names
                                     // (view_payments / manage_payments) and apiBase
  label: 'Payments',                 // optional, defaults to entity capitalized
  apiBase: moduleApi,

  //api endpint for importing data from csv
  importDataEndpoint : apiRoutes.payments.import,

  // Page-level UI gate — checked once, for the WHOLE grid AND the WHOLE
  // profile/form page, via mosyACTRLHasRole. No moduleRole set -> open to
  // anyone (same additive convention as every other role/flag in this
  // file). This is a different layer than the per-action `role` flag
  // inside individual moduleActions entries below: moduleRole controls
  // whether someone can reach the page at all; a per-action role controls
  // whether one specific button shows up once they're already in. Same
  // UI-only caveat as those: route.js needs the equivalent server-side
  // check for this to be real enforcement, not just hiding.
  moduleRole: 'view_payments',


  gridOptions : {
   checkBoxes : false,
   checkFunction : "gridCheckBoxAction"  
  },

  multiGridRows: [
    // {
    //   key: 'order_items',
    //   parentTable: 'gps_logs',
    //   title: 'Log summary',
    //   columns: [
    //     { key: 'speed', label: 'Speed' },
    //     { key: 'latitude', label: 'Lat' },
    //     { key: 'longitude', label: 'Long' , sum: true},
    //     { key: 'remark', label: 'Selling price' }
    //   ],
    //   viewMoreLink: '../gpslogs/list',
    //   filter: { order_id: '{record_id}' },
    // },
  ],

  rowLinks: [],

  // Actions available from the list view, form and grid in display order.
  //{ 
  // key: 'filter_by_client', -- name of the action 
  // label: 'Filter by account', -- button label 
  // icon: 'user', -- icon of the buttons
  // grid:true, -- show on grid or not, 
  // type: 'action', -- indicates action on form registry 
  // form: false, -- show on form or not, 
  // rowAction: false --show on row drop down or not
  // variant : 'outline-primary', -- button color  variant
  // navigateTo: '/supererpv5/revenueplan/profile', -- route to navigate to -  for link buttons only 
  // colorClass:"bg-success text-white", -- button color classname 
  // confirm: 'Are you sure you want to delete this revenueplan?', -- confirmation message for delete button
  // editOnly: true, -- show on edit only or not
  // role: 'manage_revenueplan' -- role required for this action
  //},

  profileActions: [
    { key: 'back', label: 'Back to list', icon: 'arrow-left', variant: 'outline-secondary', navigateTo: '/simukopa/payments/list', grid: false, form: true },
    { key: 'save', label: 'Save', icon: 'save', variant: 'primary', grid: false, form: true, rowAction: false },
    { key: 'delete', label: 'Delete', icon: 'trash', variant: 'outline-danger', confirm: 'Are you sure you want to delete this payment?', editOnly: true, grid: false, form: true, rowAction: true, role: 'manage_payments' },
    { key: 'view', label: 'View more', icon: 'edit', rowAction: true },
    { key: 'new', label: 'New Payment', icon: 'plus', variant: 'outline-primary', navigateTo: '/simukopa/payments/profile', grid: true, form: false, rowAction: false },
    { key: 'clone', label: 'Clone Record', icon: 'copy', variant: 'outline-secondary', editOnly: true, grid: false, form: true, rowAction: false, role: 'manage_payments' },

    // Grid-toolbar smart filters (combine, so they AND together) — handlers in logicControl/actionsRegistry.js.
    { key: 'filter_by_client', label: 'Client', icon: 'user', variant: 'outline-secondary', type: 'action', grid: true, form: false, rowAction: false },
    { key: 'filter_by_date', label: 'Date', icon: 'calendar', variant: 'outline-secondary', type: 'action', grid: true, form: false, rowAction: false },
    { key: 'filter_by_status', label: 'Status', icon: 'filter', variant: 'outline-secondary', type: 'action', grid: true, form: false, rowAction: false },

    // Jump to / scope by the linked records — same popup pattern
    // loanapplications/loans/deviceallocations use. Handlers in
    // logicControl/actionsRegistry.js.
    { key: 'view_payment_history', label: 'Payment History', icon: 'clock', variant: 'outline-secondary', type: 'action', editOnly: true, grid: false, form: true, rowAction: true },
    { key: 'view_client', label: 'View Client', icon: 'user', variant: 'outline-secondary', type: 'action', editOnly: true, grid: false, form: true, rowAction: true },
    { key: 'view_loan', label: 'View Loan', icon: 'file-text', variant: 'outline-secondary', type: 'action', editOnly: true, grid: false, form: true, rowAction: true },
  ],



  // customBlocks — the escape hatch for UI that doesn't fit the rigid
  // field-grid: a raw component, handed the SAME values/setValue/errors/
  // schema/isEditing/row context a real field gets. A block's `key` just
  // sits in a section's `fields` array exactly like a real field key —
  // wherever it appears there is where it renders. Empty by default;
  // uncomment and point at a real component when a field needs custom UI
  // (see SCHEMA-SPEC.md for the full pattern, e.g. companies/schema.js).
  customBlocks: [
    // { key: 'some_field', component: SomeComponent, colSpan: 7 },
  ],

  fieldGroups: [],
  // Field keys shown as columns in list view, in display order. IDs stay
  // on every row for actions/relationships; client_name/loan_ref
  // (computed, see fields[] below) are what's actually shown as columns.
  showInList: ['row_count', 'payment_id', 'client_name', 'loan_ref', 'payment_method', 'amount', 'transaction_reference', 'status', 'payment_date'],

  //export columns these columns are used to generate upload csv template file
  exportColumns: ['payment_id', 'client_id', 'loan_id', 'installment_id', 'payment_method', 'amount', 'currency'],

  sections: [
    { key: 'basic_information', label: 'Basic Information', columns: 3, fields: ['payment_id', 'client_id', 'loan_id', 'installment_id', 'payment_method', 'amount', 'currency'] },
    { key: 'other_details', label: 'Other Details', columns: 3, fields: ['transaction_reference', 'external_reference', 'payment_date', 'status', 'notes'] },
  ],

  fields: [
    // key: DB column name | label: shown on screen | type: drives input + SQL type
    { key: 'primkey', label: 'Primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', label: 'Record Id', type: 'text', system: true, editable: false },
    { key: 'payment_id', label: 'Payment Id', type: 'text' },
    // liveSearch picker (basic_information section) + its cached display
    // name (client_name, used in showInList) — resolved from
    // globalRelations via resolveField, same convention loanapplications/
    // phones/loans/deviceallocations use.
    ...resolveField('client_id', { as: 'client_name', colSpan: 4 }),
    { key: 'loan_id', label: 'Loan Id', type: 'text' },
    { key: 'installment_id', label: 'Installment Id', type: 'text' },
    { key: 'payment_method', label: 'Payment Method', type: 'text' },
    { key: 'amount', label: 'Amount', type: 'money' },
    { key: 'currency', label: 'Currency', type: 'groupedSelect',endpoint: moduleApi, groupByField: 'currency' },
    { key: 'transaction_reference', label: 'Ref No.', type: 'text' },
    { key: 'external_reference', label: 'External Reference', type: 'text' },
    { key: 'payment_date', label: 'Payment Date', type: 'datetime' },
    { key: 'allocated_amount', label: 'Allocated Amount', type: 'money' },
    { key: 'unallocated_amount', label: 'Unallocated Amount', type: 'money' },
    { key: 'status', label: 'Status', type: 'groupedSelect', endpoint: moduleApi, groupByField: 'status' },
    { key: 'reversal_reason', label: 'Reversal Reason', type: 'textarea' },
    { key: 'notes', label: 'Notes', type: 'textarea', colSpan: 12 },
    { key: 'created_by', label: 'Created By', type: 'text' },
    { key: 'reg_date', label: 'Reg Date', type: 'datetime' },
    { key: 'row_count', label: '#', type: 'number', computed: true, editable: false },

    // Display-only — resolved via batchMutations "join" (api schema.js).
    // loan_id/installment_id above remain the real FK values.
    { key: 'loan_ref', label: 'Loan Ref', type: 'text', computed: true, editable: false },
    { key: 'installment_number', label: 'Installment #', type: 'number', computed: true, editable: false },
    //  live search field sample 
    // { key: 'permissions', label: 'Permissions',
    //   type: 'liveSearch', colSpan: 6,
    //   endpoint: '/api/assetguard/systemmodules',
    //   searchTable: 'system_modules',
    //   valueField: 'record_id',      // id column on system_modules
    //   displayField: 'module_name',  // label column on system_modules — what search results/defaultValue text actually render
    //   labelKey: 'permission_name',  // cached label already joined onto THIS row (system_roles) — only used to seed defaultValue on load
    // },
    // more fields... see SCHEMA-SPEC.md for the full field option list
    // (searchable, editable, options, priority, db overrides)
  ],

  filters: [
    { key: 'all', label: 'All', query: {} },
  ],

  actions: [
    // { key: 'some_action', label: 'Do Something', appliesTo: { status: 'x' } },
    // "key" must match a function registered in lib/actionsRegistry.js
  ],

// for button color classes  
// dyn-btn-accent-amber  { border-color: transparent; color: #b45309; }
// dyn-btn-accent-green  { border-color: transparent; color: #047857; }
// dyn-btn-accent-purple { border-color: transparent; color: #6d28d9; }
// dyn-btn-accent-pink   { border-color: transparent; color: #be185d; }
// dyn-btn-accent-red    { border-color: transparent; color: #b91c1c; }
// dyn-btn-accent-yellow { border-color: transparent; color: #a16207; }
// dyn-btn-accent-blue   { border-color: transparent; color: #1d4ed8; }
// dyn-btn-accent-teal   { border-color: transparent; color: #0f766e; }

  // Optional: only needed if permission keys don't follow the
  // view_<entity> / manage_<entity> default.
  // roles: { view: 'view_payments', manage: 'manage_payments' },
};
