// Auto-generated by db-cli.js — BACKEND schema (trimmed).
// This is the data-shape-only counterpart to the frontend schema.js at the
// matching app/ path. It intentionally does NOT include showInList,
// profileActions, apiBase, rowLinks, customBlocks, sections, moduleRole,
// filters, or actions — those are UI concerns and live in the frontend
// schema only. Field entries also omit `label` here (UI-only display
// text) even though the frontend fields carry it. Edit
// fields/batchMutations/roles here; edit everything else there. Keep the
// `fields` array in sync between the two by regenerating both together
// (this tool writes both from the same column read).

import { resolveJoin } from '../../simukopaSchema';

export const DeviceallocationsSchema = {
  entity: 'device_allocations',

  moduleRole: 'view_device_allocations',

  fields: [
    // key: DB column name | type: drives SQL/validation (label omitted —
    // UI-only, lives in the frontend schema)
    { key: 'primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', type: 'text', system: true, editable: false },
    { key: 'phone_id', type: 'text', searchable: true },
    { key: 'client_id', type: 'text', searchable: true },
    { key: 'loan_id', type: 'text', searchable: true },
    { key: 'allocation_date', type: 'datetime' },
    { key: 'handover_date', type: 'datetime' },
    { key: 'return_date', type: 'datetime' },
    { key: 'condition_at_handover', type: 'text', searchable: true },
    { key: 'condition_at_return', type: 'text', searchable: true },
    { key: 'status', type: 'groupedSelect', endpoint: '/api/simukopa/deviceallocations/list', groupByField: 'status', searchable: true },
    { key: 'notes', type: 'textarea', colSpan: 3, searchable: true },
    { key: 'allocated_by', type: 'text', searchable: true },
    { key: 'reg_date', type: 'datetime' },
    { key: 'hive_site_id', type: 'text', searchable: true },
    { key: 'hive_site_name', type: 'text', title: true, searchable: true },
    { key: 'plan', type: 'text', searchable: true },
    { key: 'deposited_amount', type: 'money' },
    { key: 'last_payment', type: 'text', searchable: true },
    { key: 'device_status', type: 'text', searchable: true },
    { key: 'row_count', type: 'number', computed: true, editable: false },

    // Readonly payment-summary — resolved via batchMutations "join"/"sum"/
    // "compute" below, not real columns on this table.
    { key: 'amount_paid', type: 'money', computed: true, editable: false },
    { key: 'balance', type: 'money', computed: true, editable: false },
  ],

  // Optional: joins enriching each row with data from another table.
  // client/phone/loan FK lookups go through resolveJoin (globalRelations,
  // ../../simukopaSchema.js) — same convention loanapplications/phones/
  // loans use. loans.loan_id is the human-readable code (LNxxxxxxx) —
  // device_allocations.loan_id is the FK (loans.record_id), so resolveJoin
  // aliases the cached column to loan_ref (via 'as') so it never gets
  // confused with the raw FK.
  batchMutations: {
    ...resolveJoin('client_id', { as: 'client_name' }),
    ...resolveJoin('phone_id', { as: 'phone_name' }),
    ...resolveJoin('loan_id', { as: 'loan_ref' }),
    // resolveJoin('loan_id', ...) above only caches ONE column (loan_ref) —
    // this pulls the loan's total_amount too, under its own alias, for the
    // balance compute below. Unlike loan_applications, device_allocations.
    // loan_id is a DIRECT one-hop FK (loans.record_id), so no
    // reverse-join/hydration trick needed here.
    loanTotalJoin: {
      type: 'join', table: 'loans', link: 'loan_id:record_id',
      select: { loan_total_amount: 'total_amount' },
    },
    // Sum of payments.amount against this allocation's loan — covers the
    // deposit too: the loan-allocation wizard records it as an ordinary
    // payments row against the same loan_id.
    amount_paid: {
      type: 'sum', table: 'payments', column: 'amount', link: 'loan_id:record_id',
    },
    balance: {
      type: 'compute', expr: 'loan_total_amount - amount_paid',
    },
  },

  roles: { view: 'view_deviceallocations', manage: 'manage_deviceallocations' },
};
