// Auto-generated by db-cli.js — BACKEND schema (trimmed).
// This is the data-shape-only counterpart to the frontend schema.js at the
// matching app/ path. It intentionally does NOT include showInList,
// profileActions, apiBase, rowLinks, customBlocks, sections, moduleRole,
// filters, or actions — those are UI concerns and live in the frontend
// schema only. Field entries also omit `label` here (UI-only display
// text) even though the frontend fields carry it. Edit
// fields/batchMutations/roles here; edit everything else there. Keep the
// `fields` array in sync between the two by regenerating both together
// (this tool writes both from the same column read).

import { resolveJoin } from '../../simukopaSchema';

export const PhonesSchema = {
  entity: 'phones',

  moduleRole: 'view_phones',

  fields: [
    // key: DB column name | type: drives SQL/validation (label omitted —
    // UI-only, lives in the frontend schema)
    { key: 'primkey', label: 'Primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', label: 'Record Id', type: 'text', system: true, editable: false },
    { key: 'photo', label: 'Photo', type: 'image', colSpan: 12, imageClass: 'useravatar_120' },
    { key: 'model_name', label: 'Model name', type: 'text' },
    { key: 'imei_1', label: 'Imei 1', type: 'text' },
    { key: 'imei_2', label: 'Imei 2', type: 'text' },
    { key: 'selling_price', label: 'Selling Price', type: 'text' },
    { key: 'installment_price', label: 'Installment Price', type: 'text' },
    { key: 'brand_name', label: 'Brand Name', type: 'text' },
    { key: 'serial_number', label: 'Serial Number', type: 'text' },
    { key: 'phone_number', label: 'Phone Number', type: 'text' },
    { key: 'purchase_price', label: 'Purchase Price', type: 'money' },
    { key: 'status', label: 'Status', type: 'groupedSelect'},
    { key: 'lock_status', label: 'Lock Status', type: 'text', searchable: true },
    { key: 'condition_status', label: 'Condition Status', type: 'text' },
    { key: 'location', label: 'Location', type: 'text' },
    { key: 'assigned_client_id', label: 'Assigned Client Id', type: 'text' },
    { key: 'assigned_loan_id', label: 'Assigned Loan Id', type: 'text' },
    { key: 'received_date', label: 'Received Date', type: 'datetime' },
    { key: 'allocated_date', label: 'Allocated Date', type: 'datetime' },
    { key: 'notes', label: 'Notes', type: 'textarea', colSpan: 3 },
    { key: 'reg_date', label: 'Reg Date', type: 'datetime' },
    { key: 'row_count', label: '#', type: 'number', computed: true, editable: false },

    // Display-only — resolved via resolveJoin (globalRelations, below).
    // assigned_client_id/assigned_loan_id above remain the real FK values.
    { key: 'client_name', type: 'text', computed: true, editable: false },
    { key: 'loan_ref', type: 'text', computed: true, editable: false },
  ],

  // Optional: joins enriching each row with data from another table.
  // Same shape as your existing *BatchMutations.js files.
  batchMutations: {
    // "_staff_full_name_staff_id": {
    //   type: "join", table: "staff", link: "staff_id:record_id",
    //   select: { "_staff_full_name_staff_id": "full_name" }
    // },

    // loans.loan_id is the human-readable code (LNxxxxxxx) — phones.assigned_loan_id
    // is the FK (loans.record_id); resolveJoin aliases the cached column to
    // loan_ref (via 'as') so it never gets confused with the raw FK.
    ...resolveJoin('assigned_client_id', { as: 'client_name' }),
    ...resolveJoin('assigned_loan_id', { as: 'loan_ref' }),
  },

  roles: { view: 'view_phones', manage: 'manage_phones' },
};
