// Auto-generated by db-cli.js — BACKEND schema (trimmed).
// This is the data-shape-only counterpart to the frontend schema.js at the
// matching app/ path. It intentionally does NOT include showInList,
// profileActions, apiBase, rowLinks, customBlocks, sections, moduleRole,
// filters, or actions — those are UI concerns and live in the frontend
// schema only. Field entries also omit `label` here (UI-only display
// text) even though the frontend fields carry it. Edit
// fields/batchMutations/roles here; edit everything else there. Keep the
// `fields` array in sync between the two by regenerating both together
// (this tool writes both from the same column read).

import { resolveJoin } from '../../simukopaSchema';

export const LoanapplicationsSchema = {
  entity: 'loan_applications',

  moduleRole: 'view_loan_applications',

  fields: [
    // key: DB column name | type: drives SQL/validation (label omitted —
    // UI-only, lives in the frontend schema)
    { key: 'primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', type: 'text', system: true, editable: false },
    { key: 'application_id', type: 'text', searchable: true },
    { key: 'client_id', type: 'text', searchable: true },
    { key: 'phone_id', type: 'text', searchable: true },
    { key: 'model_id', type: 'text', searchable: true },
    { key: 'product_id', type: 'text', searchable: true },
    { key: 'requested_amount', type: 'money' },
    { key: 'deposit_amount', type: 'money' },
    { key: 'application_date', type: 'datetime' },
    { key: 'approval_date', type: 'datetime' },
    { key: 'approved_amount', type: 'money' },
    { key :"next_billing_date", label: 'Next Billing Date', type: 'datetime' },
    { key: 'rejection_reason', type: 'textarea', searchable: true },
    { key: 'status', type: 'groupedSelect', endpoint: '/api/simukopa/loanapplications/list', groupByField: 'status', searchable: true },
    { key: 'reviewed_by', type: 'text', searchable: true },
    { key: 'notes', type: 'textarea', colSpan: 3, searchable: true },
    { key: 'reg_date', type: 'datetime' },
    { key: 'hive_site_id', type: 'text', searchable: true },
    { key: 'hive_site_name', type: 'text', title: true, searchable: true },
    { key: 'row_count', type: 'number', computed: true, editable: false },

    // Readonly payment-summary — resolved via batchMutations "join"/"sum"/
    // "compute" below, not real columns on this table.
    { key: 'amount_paid', type: 'money', computed: true, editable: false },
    { key: 'balance', type: 'money', computed: true, editable: false },
  ],

  // Optional: joins enriching each row with data from another table.
  // Same shape as your existing *BatchMutations.js files.
  //
  // client/phone/model FK lookups go through resolveJoin (globalRelations,
  // ../../simukopaSchema.js) — same convention imsv2 uses. Each only
  // caches ONE column (globalRelations' cacheField), so client_name is
  // just clients.first_name and phone_name just phones.model_name — no
  // concat of first+last or brand+model anymore, that was a hand-rolled
  // one-off before this schema switched over to the shared helper.
  batchMutations: {
    ...resolveJoin('client_id', { as: 'client_name' }),
    ...resolveJoin('phone_id', { as: 'phone_name' }),
    ...resolveJoin('model_id', { as: 'model_name' }),
    // NOT resolveJoin('product_id', ...): globalRelations' product_id
    // entry points at `financing_products`, but the loan-allocation wizard
    // (app/api/simukopa/loanallocation/route.js) actually writes
    // loan_plans.record_id into this column — confirmed against the live
    // DB. That globalRelations entry is stale/wrong for this table; using
    // it here would silently resolve every product_name to null. Left
    // hand-written until schemamap.txt's spec is corrected and
    // regenerated.
    productJoin: {
      type: 'join', table: 'loan_plans', link: 'product_id:record_id',
      select: { product_name: 'plan_name' },
    },
    // loans.application_id points BACK at this application (reverse of
    // every FK above) — pulled in just to carry loan_record_id forward
    // into the amountPaid sum below (mosyEnrichFinalResponse hydrates
    // each later mutation with everything enriched so far, so this join
    // has to be declared before amountPaid).
    loanJoin: {
      type: 'join', table: 'loans', link: 'record_id:application_id',
      select: { loan_record_id: 'record_id' },
    },
    // Sum of payments.amount against the loan this application produced
    // (payments.loan_id -> loans.record_id, pulled in by loanJoin above —
    // loan_applications itself has no direct FK to payments/loans).
    // Covers the deposit too: the loan-allocation wizard records it as an
    // ordinary payments row against the same loan_id.
    amount_paid: {
      type: 'sum', table: 'payments', column: 'amount', link: 'loan_id:loan_record_id',
    },
    // Falls back to requested_amount while the application isn't approved
    // yet (approved_amount is 0/blank pre-approval).
    balance: {
      type: 'compute', expr: '(approved_amount || requested_amount) - amount_paid',
    },
  },

  roles: { view: 'view_loanapplications', manage: 'manage_loanapplications' },
};
