// Auto-generated by db-cli.js — BACKEND schema (trimmed).
// This is the data-shape-only counterpart to the frontend schema.js at the
// matching app/ path. It intentionally does NOT include showInList,
// profileActions, apiBase, rowLinks, customBlocks, sections, moduleRole,
// filters, or actions — those are UI concerns and live in the frontend
// schema only. Field entries also omit `label` here (UI-only display
// text) even though the frontend fields carry it. Edit
// fields/batchMutations/roles here; edit everything else there. Keep the
// `fields` array in sync between the two by regenerating both together
// (this tool writes both from the same column read).

import { resolveJoin } from '../../simukopaSchema';

export const PaymentsSchema = {
  entity: 'payments',

  moduleRole: 'view_payments',

  fields: [
    // key: DB column name | type: drives SQL/validation (label omitted —
    // UI-only, lives in the frontend schema)
    { key: 'primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', type: 'text', system: true, editable: false },
    { key: 'payment_id', type: 'text', searchable: true },
    { key: 'client_id', type: 'text', searchable: true },
    { key: 'loan_id', type: 'text', searchable: true },
    { key: 'installment_id', type: 'text', searchable: true },
    { key: 'payment_method', type: 'text', searchable: true },
    { key: 'amount', type: 'money' },
    { key: 'currency', type: 'text', searchable: true },
    { key: 'transaction_reference', type: 'text', searchable: true },
    { key: 'external_reference', type: 'text', searchable: true },
    { key: 'payment_date', type: 'datetime' },
    { key: 'allocated_amount', type: 'money' },
    { key: 'unallocated_amount', type: 'money' },
    { key: 'status', type: 'groupedSelect', endpoint: '/api/simukopa/payments/list', groupByField: 'status', searchable: true },
    { key: 'reversal_reason', type: 'textarea', searchable: true },
    { key: 'notes', type: 'textarea', colSpan: 3, searchable: true },
    { key: 'created_by', type: 'text', searchable: true },
    { key: 'reg_date', type: 'datetime' },
    { key: 'hive_site_id', type: 'text', searchable: true },
    { key: 'hive_site_name', type: 'text', title: true, searchable: true },
    { key: 'row_count', type: 'number', computed: true, editable: false },
  ],

  // Optional: joins enriching each row with data from another table.
  // Same shape as your existing *BatchMutations.js files.
  batchMutations: {
    // client_id FK lookup goes through resolveJoin (globalRelations,
    // ../../simukopaSchema.js) — same convention loanapplications/phones/
    // loans/deviceallocations use.
    ...resolveJoin('client_id', { as: 'client_name' }),
    // loans.loan_id is the human-readable code — payments.loan_id is the
    // FK (loans.record_id), aliased to loan_ref to keep the two distinct.
    loanJoin: {
      type: 'join', table: 'loans', link: 'loan_id:record_id',
      select: { loan_ref: 'record_id' },
    },
    installmentJoin: {
      type: 'join', table: 'loan_installments', link: 'installment_id:record_id',
      select: { installment_number: 'installment_number' },
    },
  },

  roles: { view: 'view_payments', manage: 'manage_payments' },
};
