// This is the ONLY file that changes when you clone this module.
// See SCHEMA-SPEC.md for the full reference — quick version below.
// Rough cut auto-generated by db-cli.js (rule-based column-name matching,
// no AI) — hand-tune sections/profileActions/groupedSelect below same as
// any other cloned module.
//
// FRONTEND schema — full UI shape (showInList, profileActions, apiBase,
// rowLinks, customBlocks, sections, moduleRole, etc). The trimmed backend
// counterpart lives alongside this at the api/ path and only carries
// entity/fields/batchMutations/roles.

import { getApiRoutes } from '../AppRoutes/apiRoutesHandler';
// Use default base root (/)
const apiRoutes = getApiRoutes();
const moduleApi = apiRoutes.clients.base;

export const ClientsSchema = {
  entity: 'clients',              // DB table name; also drives default role names
                                     // (view_clients / manage_clients) and apiBase
  label: 'Clients',                 // optional, defaults to entity capitalized
  apiBase: moduleApi,

  //api endpint for importing data from csv
  importDataEndpoint : apiRoutes.clients.import,

  // Page-level UI gate — checked once, for the WHOLE grid AND the WHOLE
  // profile/form page, via mosyACTRLHasRole. No moduleRole set -> open to
  // anyone (same additive convention as every other role/flag in this
  // file). This is a different layer than the per-action `role` flag
  // inside individual moduleActions entries below: moduleRole controls
  // whether someone can reach the page at all; a per-action role controls
  // whether one specific button shows up once they're already in. Same
  // UI-only caveat as those: route.js needs the equivalent server-side
  // check for this to be real enforcement, not just hiding.
  moduleRole: 'view_clients',


  gridOptions : {
   checkBoxes : false,
   checkFunction : "gridCheckBoxAction"  
  },

  multiGridRows: [
    // {
    //   key: 'order_items',
    //   parentTable: 'gps_logs',
    //   title: 'Log summary',
    //   columns: [
    //     { key: 'speed', label: 'Speed' },
    //     { key: 'latitude', label: 'Lat' },
    //     { key: 'longitude', label: 'Long' , sum: true},
    //     { key: 'remark', label: 'Selling price' }
    //   ],
    //   viewMoreLink: '../gpslogs/list',
    //   filter: { order_id: '{record_id}' },
    // },
  ],

  rowLinks: [],

  // Actions available from the list view, form and grid in display order.
  //{ 
  // key: 'filter_by_client', -- name of the action 
  // label: 'Filter by account', -- button label 
  // icon: 'user', -- icon of the buttons
  // grid:true, -- show on grid or not, 
  // type: 'action', -- indicates action on form registry 
  // form: false, -- show on form or not, 
  // rowAction: false --show on row drop down or not
  // variant : 'outline-primary', -- button color  variant
  // navigateTo: '/supererpv5/revenueplan/profile', -- route to navigate to -  for link buttons only 
  // colorClass:"bg-success text-white", -- button color classname 
  // confirm: 'Are you sure you want to delete this revenueplan?', -- confirmation message for delete button
  // editOnly: true, -- show on edit only or not
  // role: 'manage_revenueplan' -- role required for this action
  //},

  profileActions: [
    { key: 'back', label: 'Back to list', icon: 'arrow-left', variant: 'outline-secondary', navigateTo: '/simukopa/clients/list', grid: false, form: true },
    { key: 'save', label: 'Save', icon: 'save', variant: 'primary', grid: false, form: true, rowAction: false },
    { key: 'delete', label: 'Delete', icon: 'trash', variant: 'outline-danger', confirm: 'Are you sure you want to delete this client?', editOnly: true, grid: false, form: true, rowAction: true, role: 'manage_clients' },
    { key: 'view', label: 'View more', icon: 'edit', rowAction: true },
    { key: 'new', label: 'New Client Account', icon: 'user-plus', variant: 'outline-primary', navigateTo: '/simukopa/clients/profile', grid: true, form: false, rowAction: false },
    { key: 'clone', label: 'Clone Record', icon: 'copy', variant: 'outline-secondary', editOnly: true, grid: false, form: true, rowAction: false, role: 'manage_clients' },
    //{ key: 'filterByDate', label: 'Filter by date', icon: 'calendar', variant: 'outline-primary', type: 'action', grid: true, form: false, rowAction: false },

    // Popup the devices allocated to this client (deviceallocations scoped
    // by client_id) — handler in logicControl/actionsRegistry.js.
    { key: 'view_device_allocations', label: 'Device Allocations', icon: 'mobile', variant: 'outline-secondary', type: 'action', editOnly: true, grid: false, form: true, rowAction: true },
  ],



  // customBlocks — the escape hatch for UI that doesn't fit the rigid
  // field-grid: a raw component, handed the SAME values/setValue/errors/
  // schema/isEditing/row context a real field gets. A block's `key` just
  // sits in a section's `fields` array exactly like a real field key —
  // wherever it appears there is where it renders. Empty by default;
  // uncomment and point at a real component when a field needs custom UI
  // (see SCHEMA-SPEC.md for the full pattern, e.g. companies/schema.js).
  customBlocks: [
    // { key: 'some_field', component: SomeComponent, colSpan: 7 },
  ],

  fieldGroups: [],
  // Field keys shown as columns in list view, in display order.
  showInList: ['row_count', 'photo','client_number', 'first_name', 'middle_name', 'last_name', 'id_number', 'phone_number', 'total_issued', 'total_paid', 'balance'],

  //export columns these columns are used to generate upload csv template file
  exportColumns: ['client_number', 'first_name', 'middle_name', 'last_name', 'id_number', 'id_type', 'phone_number'],

  sections: [
    { key: 'basic_information', label: 'Basic Information', columns: 3, fields: ['photo','client_number', 'first_name', 'middle_name', 'last_name', 'id_number', 'id_type', 'phone_number'] },
    { key: 'other_details', label: 'Other Details', columns: 3, fields: ['alternative_phone', 'email', 'date_of_birth', 'gender', 'county', 'town', 'address', 'occupation', 'employer', 'monthly_income', 'status', 'notes', 'reg_date'] },
    { key: 'loan_summary', label: 'Loan Summary', columns: 3, fields: ['total_issued', 'total_paid', 'balance'] },
  ],

  fields: [
    // key: DB column name | label: shown on screen | type: drives input + SQL type
    { key: 'primkey', label: 'Primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', label: 'Record Id', type: 'text', system: true, editable: false },
    { key: 'client_number', label: 'Account Number', type: 'text', editable: false , editOnly: true},
    { key: 'first_name', label: 'First Name', type: 'text', title: true, required: true },
    { key: 'middle_name', label: 'Middle Name', type: 'text', title: true },
    { key: 'last_name', label: 'Last Name', type: 'text', title: true, required: true },
    { key: 'id_number', label: 'Id / Passport Number', type: 'text' },
    { key: 'id_type', label: 'Id Type', type: 'select', options:[ 'National ID', 'Passport', 'Drivers License'] },
    { key: 'phone_number', label: 'Phone Number', type: 'text' },
    { key: 'alternative_phone', label: 'Alternative Phone', type: 'text' },
    { key: 'email', label: 'Email', type: 'text' },
    { key: 'date_of_birth', label: 'Date Of Birth', type: 'datetime' },
    { key: 'gender', label: 'Gender', type: 'select', options:[ 'Male', 'Female'] },
    { key: 'county', label: 'County', type: 'groupedSelect', endpoint: moduleApi, groupByField: 'county' },
    { key: 'town', label: 'Town', type: 'groupedSelect', endpoint: moduleApi, groupByField: 'town' },
    { key: 'address', label: 'Address', type: 'text'},
    { key: 'occupation', label: 'Occupation', type: 'groupedSelect', endpoint: moduleApi, groupByField: 'occupation' },
    { key: 'employer', label: 'Employer', type: 'text' },
    { key: 'monthly_income', label: 'Monthly Income', type: 'money' },
    { key: 'status', label: 'Status', type: 'groupedSelect', endpoint: moduleApi, groupByField: 'status' },
    { key: 'kyc_status', label: 'Kyc Status', type: 'text' },
    { key: 'notes', label: 'Notes', type: 'textarea', colSpan: 12 },
    { key: 'created_by', label: 'Created By', type: 'text' },
    { key: 'reg_date', label: 'Registration Date', type: 'datetime', editable: false },
    { key: 'photo', label: 'Photo', type: 'image',  colSpan:12 , imageClass:'useravatar_120' },
    { key: 'row_count', label: '#', type: 'number', computed: true, editable: false },

    // Readonly loan-summary totals — resolved server-side via batchMutations
    // "sum"/"compute" (api schema.js), not real columns on this table.
    { key: 'total_issued', label: 'Total Issued', type: 'money', computed: true, editable: false, sum: true },
    { key: 'total_paid', label: 'Total Paid', type: 'money', computed: true, editable: false, sum: true },
    { key: 'balance', label: 'Balance', type: 'money', computed: true, editable: false, sum: true },
    //  live search field sample 
    // { key: 'permissions', label: 'Permissions',
    //   type: 'liveSearch', colSpan: 6,
    //   endpoint: '/api/assetguard/systemmodules',
    //   searchTable: 'system_modules',
    //   valueField: 'record_id',      // id column on system_modules
    //   displayField: 'module_name',  // label column on system_modules — what search results/defaultValue text actually render
    //   labelKey: 'permission_name',  // cached label already joined onto THIS row (system_roles) — only used to seed defaultValue on load
    // },
    // more fields... see SCHEMA-SPEC.md for the full field option list
    // (searchable, editable, options, priority, db overrides)
  ],

  filters: [
    { key: 'all', label: 'All', query: {} },
  ],

  actions: [
    // { key: 'some_action', label: 'Do Something', appliesTo: { status: 'x' } },
    // "key" must match a function registered in lib/actionsRegistry.js
  ],

// for button color classes  
// dyn-btn-accent-amber  { border-color: transparent; color: #b45309; }
// dyn-btn-accent-green  { border-color: transparent; color: #047857; }
// dyn-btn-accent-purple { border-color: transparent; color: #6d28d9; }
// dyn-btn-accent-pink   { border-color: transparent; color: #be185d; }
// dyn-btn-accent-red    { border-color: transparent; color: #b91c1c; }
// dyn-btn-accent-yellow { border-color: transparent; color: #a16207; }
// dyn-btn-accent-blue   { border-color: transparent; color: #1d4ed8; }
// dyn-btn-accent-teal   { border-color: transparent; color: #0f766e; }

  // Optional: only needed if permission keys don't follow the
  // view_<entity> / manage_<entity> default.
  // roles: { view: 'view_clients', manage: 'manage_clients' },
};
